# Generated by Django 5.0.2 on 2024-03-03 04:46

from django.db import migrations
import json
from django.conf import settings
import os

def load_matches_data(apps, schema_editor):
    Match = apps.get_model('restfulclub', 'Match')
    json_file_path = os.path.join(settings.BASE_DIR, 'matches.json')
    with open(json_file_path, 'r') as file:
        matches_data = json.load(file)
        for entry in matches_data:
            match_data = entry['fields']
            # Check if the match already exists
            if not Match.objects.filter(opponent=match_data['opponent'], match_date=match_data['match_date']).exists():
                Match.objects.create(**match_data)
            else:
                print(f"Match {match_data['opponent']} on {match_data['match_date']} already exists. Skipping.")

def load_suites_data(apps, schema_editor):
    Suite = apps.get_model('restfulclub', 'Suite')
    json_file_path = os.path.join(settings.BASE_DIR, 'suites.json')
    with open(json_file_path, 'r') as file:
        suites_data = json.load(file)
        for entry in suites_data:
            suite_data = entry['fields']
            suite, created = Suite.objects.get_or_create(
                pk=entry['pk'],
                defaults=suite_data
            )
            if created:
                print(f"Suite {suite_data['name']} created.")
            else:
                print(f"Suite {suite_data['name']} already exists. Skipping.")


class Migration(migrations.Migration):

    dependencies = [
        ('restfulclub', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_matches_data),
        migrations.RunPython(load_suites_data),
    ]
